apiVersion: apps/v1
kind: Deployment
metadata:
  name: textractify-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textractify-client
  template:
    metadata:
      labels:
        app: textractify-client
    spec:
      containers:
        - name: textractify-client
          image: frnn4268/client-textractify-client:latest
          ports:
            - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: textractify-client-service
spec:
  selector:
    app: textractify-client
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: NodePort
